### ISSUE TITLE
腾讯云函数提示错误

### ISSUE THREAD

**Issue by iptag** [BlueSkyXN/52pojie-Checkin#2]
翻下日志，从11月5号开始就报错了，今天换了cookie重新运行，还是报错，错误日志如下

START RequestId:ebb26ed2-a56e-4d73-b285-e3acc0c1a99f

Starting new HTTPS connection (1): www.52pojie.cn:443

https://www.52pojie.cn:443 "GET /home.php?mod=task&do=apply&id=2 HTTP/1.1" 200 None

Starting new HTTPS connection (1): www.52pojie.cn:443

https://www.52pojie.cn:443 "GET /home.php?mod=task&do=draw&id=2 HTTP/1.1" 200 None

ERROR RequestId:ebb26ed2-a56e-4d73-b285-e3acc0c1a99f Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 60, in main_handler\n    main()\n  File \"/var/user/index.py\", line 43, in main\n    fc=fb.find('div',id='messagetext').find('p').text\nAttributeError: 'NoneType' object has no attribute 'find'","statusCode":430}

END RequestId:ebb26ed2-a56e-4d73-b285-e3acc0c1a99f

Report RequestId:ebb26ed2-a56e-4d73-b285-e3acc0c1a99f Duration:417ms Memory:128MB MemUsage:30.230469MB

**Comment by BlueSkyXN** [comment]
我发现我日志全是失败。。。我也不知道从哪天开始了
我发现我就没签到成功过?没有签到按钮了，怕是被gank了？

**Comment by doublog** [comment]
我看了下日志，我是5号过后失败的。。

```
Traceback (most recent call last):
  File "./52.py", line 64, in <module>
    main()
  File "./52.py", line 43, in main
    fc=fb.find('div',id='messagetext').find('p').text
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by blacktitty-y** [comment]
> 现我就没签到成功过?没有签到按钮了，怕是被gan

有签到按钮啊 所以 是不是脚本要更新一下啦

**Comment by iptag** [comment]
> 我发现我日志全是失败。。。我也不知道从哪天开始了 我发现我就没签到成功过?没有签到按钮了，怕是被gank了？

大佬，有空更新一哈 👍
